sveltejs/svelte-preprocess

src/index.js, test/index.test.js
=> don't try to resolve files hosted on a cdn locally

src/index.js, src/utils.js
see also https://github.com/sveltejs/svelte-loader/issues/72 and https://github.com/sveltejs/svelte-loader/pull/75
=> add dependencies to result

src/processors/less.js, src/processors/stylus.js
Fix less and stylus stand-alone processor
=> fix: 🐛 less and stylus stand-alone processor

src/index.js
Fix stand-alone processors not exported
=> fix: 🐛 stand-alone processors not exported

README.md, package-lock.json, package.json, src/index.d.ts, src/index.js, src/processors/typescript.js, src/transformers/typescript.js, src/utils.js, test/autoProcess/script.test.js, test/fixtures/script.coffee, test/fixtures/script.js, test/fixtures/script.ts, test/fixtures/tsconfig.json, test/fixtures/tsconfig.semantic.json, test/fixtures/tsconfig.syntactic.json
=> feat: 🎸 add typescript preprocessor

CHANGELOG.md, examples/sapper-rollup/package-lock.json, examples/sapper-rollup/package.json, examples/sapper-rollup/rollup.config.js, examples/svelte-rollup/package-lock.json, examples/svelte-rollup/package.json, examples/svelte-rollup/rollup.config.js, src/transformers/stylus.ts, src/transformers/typescript.ts
=> fix: typescript imports on windows and unused imports

CHANGELOG.md, README.md, package.json, src/autoProcess.ts, src/transformers/globalStyle.ts, src/transformers/scss.ts, src/transformers/typescript.ts, src/types/options.ts, src/utils.ts, test/transformers/less.test.ts, test/transformers/scss.test.ts, yarn.lock
Initial implementation of #148
=> Add compiler option for scss

docs/preprocessing.md
This PR relates to the following issue: https://github.com/sveltejs/svelte-preprocess/issues/212
I added an option to the preprocessor documentation.
=> added the `configFilePath` option to the PostCSS preprocessor documentation.

.eslintrc, .github/workflows/ci.yml, package.json, src/autoProcess.ts, src/modules/language.ts, test/autoProcess/script.test.ts, test/autoProcess/sourceMaps.test.ts, test/transformers/pug.test.ts, yarn.lock
=> fix: 🐛 language specific options not being set

CHANGELOG.md, package.json, src/modules/tagInfo.ts, test/autoProcess/externalFiles.test.ts
=> fix: 🐛 self-closing templates with external source

docs/preprocessing.md, src/transformers/pug.ts
=> This PR adds missing Pug syntax mixin `+html()`

.github/PULL_REQUEST_TEMPLATE.md, CHANGELOG.md, package.json, src/autoProcess.ts, src/modules/language.ts, src/modules/tagInfo.ts, src/modules/utils.ts, test/autoProcess/autoProcess.test.ts, test/autoProcess/externalFiles.test.ts
=> fix: 🐛 prevent trying to resolve interpolated src values

CHANGELOG.md, package.json, src/transformers/globalStyle.ts, test/transformers/globalStyle.test.ts
=> fix: 🐛 prefixed keyframes globalization

CHANGELOG.md, docs/getting-started.md, docs/preprocessing.md, package.json, src/autoProcess.ts, src/modules/language.ts, src/transformers/postcss.ts, test/processors/postcss.test.ts, test/transformers/postcss.test.ts, test/transformers/typescript.test.ts
=> feat: 🎸 add support for lang=sugarss & type=text/sugarss

test/transformers/postcss.test.ts
The other PRs are failing because of this lint failure
=> Fix lint failure

docs/getting-started.md
I noticed that the change from this PR disappeared from the main branch:
https://github.com/sveltejs/svelte-preprocess/pull/276
Indeed there seem to be no commits between the 23rd of October and 17th of November on the main branch. And this was merged to master on the 2nd of November. Does this have anything to do with the change branch change from master to main?
Anyhows, here I am submitting to main again.
=> Document how to make defaults work with the extension

.github/workflows/ci.yml, CHANGELOG.md, package.json, src/modules/markup.ts, src/modules/tagInfo.ts, test/autoProcess/markup.test.ts
Fixes the technical issue in #310
=> Less greedy markup regexp

src/transformers/typescript.ts
=> fix: support ts build with no tsconfig.json

README.md, docs/usage.md
=> docs: adjust config for esm usage

src/processors/coffeescript.ts, src/processors/less.ts, src/processors/scss.ts, src/processors/stylus.ts, src/processors/typescript.ts, test/processors/coffeescript.test.ts, test/processors/less.test.ts, test/processors/scss.test.ts, test/processors/stylus.test.ts, test/processors/typescript.test.ts
=> Fixes prepend data being injected in other languages

src/transformers/typescript.ts
=> (fix) fallback to empty string if there are no attributes

src/transformers/typescript.ts, test/fixtures/TypeScriptImports.svelte
=> (fix) add quotes to ts store regex

src/transformers/typescript.ts, test/fixtures/TypeScriptImports.svelte, test/transformers/typescript.test.ts
=> (fix) handle $store imported in module script

src/transformers/typescript.ts
#383
This saves about 5 miliseconds per file on the project I tested
=> (perf) cache tsconfig

package.json
=> [less] accept v4 as peer dep

package.json
Was accidentally bumped in another commit
=> fix: adjust typescript peer dep

docs/preprocessing.md, src/transformers/pug.ts
Problem with const mixin in pug
https://github.com/sveltejs/svelte-preprocess/discussions/467
=> fix: add mixin const (#467)

package.json
Fixes https://github.com/sveltejs/svelte-preprocess/issues/628
=> fix: remove pnpm version restriction

.husky/commit-msg, .husky/post-merge, .husky/pre-commit, .husky/pre-push, package.json, pnpm-lock.yaml
This is broken and has been for a long time, which makes working on the repo very difficult. It's unnecessary since we have the CI
=> chore: remove husky

docs/migration-guide.md
This PR adds a missing table of contents (TOC) to the Migration Guide.
=> docs: add missing TOC to Migration Guide
