- src/transformers/pug.js
- src/transformers/scss.js
- src/transformers/stylus.js
Thank you for your efforts with svelte-preprocess. I'm exploring svelte right now and prefer sass and pug. Your repo saved me the time and effort of writing my own hooks to preprocess. 👍 
Having include paths for sass and stylus is good, but unfortunately I was finding the default code paths passed in an empty options object (in [utils.js/runTransformer()](https://github.com/kaisermann/svelte-preprocess/blob/975b08f60ce0ef5d3c9a0ff3caa49949e967b274/src/utils.js#L97)). So, the include paths aren't added by default. This PR merges in the default options with `Object.assign()`. (We could reuse the `options` variable. I opted for a new `opts` variable for clarity but can change it.)
This PR also plumbs through sensible defaults for pug - the filename (fixes imports) and html as the default …
> Merge default options with provided options and provide defaults for pug

- README.md
- src/utils.js
- test/index.test.js
This is the rest of my fix - a few extra tests, but also removes the need for lang to always start with `text/`. Often json types use `application/`
> Allow short aliases to refer to application/* as well as text/* for json types

- README.md
- src/index.js
- test/index.test.js
Note, don't merge this until the other PR https://github.com/kaisermann/svelte-preprocess/pull/13 is merged - as it depends on the shorthand `application/json` -> `json` syntax used throughout the plugin, which the other pull provides!
This plugin allows certain tags to be totally excluded, such as the google markup which needs to stay intact and unbundled.
> allow ignoring of certain tags

- README.md
- package-lock.json
- package.json
- src/autoProcess.js
- src/index.js
- src/processors/coffeescript.js
- src/processors/less.js
- src/processors/postcss.js
- src/processors/pug.js
- src/processors/scss.js
- src/processors/stylus.js
- src/transformers/coffeescript.js
- src/transformers/less.js
- src/transformers/postcss.js
- src/transformers/pug.js
- src/transformers/scss.js
- src/transformers/stylus.js
- src/utils.js
- test/index.test.js
- test/utils.js
This PR keeps this package backwards compatible and introduces the optional standalone processors in case someone wants configure their preprocess step using [v3 preprocessors list](https://v3.svelte.technology/docs#svelte-preprocess).
TODO: standalone processors documentation
> Add v3 support

- README.md
- src/autoProcess.js
- src/index.js
- src/processors/globalStyle.js
- src/transformers/globalStyle.js
- src/utils.js
- test/transformers/globalStyle.test.js
Use `globalStyle` preprocess or `global` attribute to apply styles to a selector globally.
```html
<style global lang="scss">
$color: red;
div {
color: $color;
}
</style>
```
```js
import { scss, globalStyle } from 'svelte-preprocess'
svelte.preprocess(input, [
globalStyle(),
]).then(...)
```
> feat: 🎸 global style

- src/transformers/globalStyle.js
- test/transformers/globalStyle.test.js
Prefix all @keyframe at-rule names with '-global-'.
For example:
@keyframes slide-in {from{} to{}}
will become:
@keyframes -global-slide-in {from{} to{}}
> Make @keyframe at-rules global.

- README.md
According to the source code the Sass-transformer works with `node-sass` or `sass`, but there is no notes about it in the README.
I've added installation line just to mark this fact, because it is important. My first impression was that it can't work with `sass`.
> Add `sass` installation line to README

- README.md
> docs(readme): document unsupported TS compiler options

- README.md
- src/transformers/scss.ts
- src/types/options.ts
- test/transformers/scss.test.ts
>When using Dart Sass, renderSync() is almost twice as fast as render() by default, due to the overhead of making the entire evaluation process asynchronous.
Just need to pass `renderSync` as `true` with scss options:
```
scss: {
includePaths: ['theme', 'src/styles'],
renderSync: true,
}
```
> add an option to render scss synchronously via renderSync

- README.md
- src/autoProcess.ts
- src/index.ts
- src/processors/replace.ts
- src/transformers/replace.ts
- src/types/index.ts
- src/types/options.ts
- src/utils.ts
- test/transformers/replace.test.ts
It came to my mind that it would useful to have an easy way to replace values inside svelte components like what `Webpack.DefinePlugin` does. I know people can use the webpack/rollup plugin instead, but adding a `markup` transformer guarantees that we're replacing values before the compilation step, which allows some interesting use cases.
> feat: 🎸 add `replace` transformer

- src/transformers/typescript.ts
- test/transformers/typescript.test.ts
Hi @kaisermann ,
Nice work on the library!
When using [Store reactive variables](https://svelte.dev/tutorial/writable-stores), e.g **$user** that are prefixed with **$**, TypeScript reports a TS2552 error: `'Cannot find name '{0}'. Did you mean '{1}'?' ` although the variable is declared and valid, so this PR supresses this error if the variable in fact exists, and we've used a similar solution to what you did with [isValidSvelteImportDiagnostic](https://github.com/kaisermann/svelte-preprocess/blob/master/src/transformers/typescript.ts#L47) .
> Avoid reporting 'Cannot find name '{0}'. Did you mean '{1}'?' for reactive variables

- README.md
This is much more modern and also necessary if you want to use `"type": "module"` in your `package.json`
> Use ES6 module imports

- CHANGELOG.md
- README.md
- package.json
- src/autoProcess.ts
- src/modules/globalifySelector.ts
- src/modules/hasPostcssInstalled.ts
- src/modules/importAny.ts
- src/processors/globalRule.ts
- src/transformers/globalRule.ts
- src/transformers/globalStyle.ts
- src/transformers/scss.ts
- src/types/index.ts
- src/utils.ts
- test/transformers/globalRule.test.ts
- test/transformers/scss.test.ts
- test/utils.test.ts
This implements the proposal discussed in Svelte RFCs: https://github.com/sveltejs/rfcs/pull/22#issuecomment-638139699
```html
<style>
.scoped-style {}
:global {
import 'global-stylesheet';
.global-style {}
}
</style>
```
This would allow for fine control of what parts of the stylesheet should be made global.
> feat: add the :global {} rule support

- CHANGELOG.md
- package.json
- src/transformers/globalRule.ts
- test/transformers/globalRule.test.ts
This is... embarrassing.
Apparently, for code like this:
```sass
:global {
/* comment */
.cls { color: red; }
}
```
Sass and Less will produce the following output:
```css
:global {
/* comment */
}
:global .cls { 
color: red; 
}
```
...which leaves us with comment-only rules that only consist of the `:global` selector, which gets lovingly transpiled into an empty string, producing things like `<style>{/* comment */}</style>`. This is to remedy that.
> Do not break when :global is the only selector

- CHANGELOG.md
- package.json
- src/modules/globalifySelector.ts
- test/modules.test.ts
- test/transformers/globalRule.test.ts
Previously, the selectors were split by a single literal space, which is rather naive. This PR allows for all kinds of whitespace, combinators like `>`, `+`, `~`, as well as spaces that aren't combinators (`[attr="with spaces"]`)
> Make the selector parsing smarter 

- package.json
In Bash, single quotes prevent variable substitution, which results in all of the releases having `Release v$npm_package_version` as their tag message. This is to fix that.
Also, it would be nice to incorporate the CHANGELOG.md into those messages as well, but I don't know how would one do that.
> Fix the quotes in the release script

- src/modules/globalifySelector.ts
- test/modules.test.ts
BREAKING CHANGE: 🧨 Uses Lookbehind assertions, so Node 9.11.2+ is needed
✅ Closes: #191
> fix: 🐛 prevent globalify to wrongly split escaped selectors

- docs/getting-started.md
The variable name in the code given as an example was wrong. It should be "name" instead of "world": {world} => {name}
> Correct a wrong variable name in the example code

- docs/preprocessing.md
The path referring to `usage.md` was leading to a 404 page, due to it's path (`docs/usage.md`) being ambiguous to the current directory, solved it simply by removing the `docs/` portion of the path
> docs: fix broken link to "Usage" section

- docs/usage.md
Fixes https://github.com/sveltejs/language-tools/issues/593 causing error https://github.com/sveltejs/language-tools/issues/593#issuecomment-703771711
> docs: change es6 import to cjs require

- .eslintrc
- .github/workflows/ci.yml
- .gitignore
- package.json
- src/modules/utils.ts
- src/transformers/scss.ts
- test/node_modules/scss-package/main.scss
- test/transformers/scss.test.ts
- yarn.lock
✅ Closes: #277
edit 1:
~Just gotta do a test for it 😁~
edit 2:
~Tests are failing now, not sure why. See https://github.com/sass/node-sass-middleware/issues/104~ Can't use the `done` for `renderSync` runs. 
Current challenge: 
it seems the sass compiler doesn't pass an importer's returned value through the `includePaths` paths, so it needs to return an absolute path. We use the `url` and `prev` (source) arguments to resolve it ~, but, for some reason, the `prev` value is coming as `stdin` instead of the importer path.~. Needed to pass `file` alongside the rest of the options.
edit 3:
Need to rewrite that importer, the logic is wrong. It will stop on the first node_modules found, even if there's no package with the specified path.
References: …
> feat: 🎸 add scss support for tilde (~) imports

- docs/usage.md
Updated docs so they don't exlcude node_modules from svelte-loader, because that makes it impossible to use Svelte components from NPM.
Also, see: https://github.com/sveltejs/template-webpack/commit/302038a740af4cff433c9d261cffc7f06f11ab9a#diff-1fb26bc12ac780c7ad7325730ed09fc4c2c3d757c276c3dacc44bfe20faf166f
> Do not exclude node_modules from svelte-loader

- src/transformers/coffeescript.ts
This fixes a VS Code warning I was getting:
> 'code' is already declared in the upper scope.
> Fix VS Code warning

- src/autoProcess.ts
- src/modules/language.ts
- src/modules/utils.ts
- src/transformers/typescript.ts
- test/autoProcess/sourceMaps.test.ts
trivial : )
edit: less trivial on second sight
in the old version, `sveltePreprocess({ sourceMap: true })` 
was translated to `transformer({ content, filename, options: { sourceMap: true } })`
but the typescript `transformer` function expects compiler-options in `options.compilerOptions`
so the correct translation is `transformer({ content, filename, options: { compilerOptions: { sourceMap: true } } })`
> fix typescript: translate options.sourceMap to options.compilerOptions.sourceMap (#286)

- src/transformers/scss.ts
- test/transformers/scss.test.ts
related to issue #286 and PR https://github.com/sveltejs/svelte/pull/5854
sourcemaps should be returned either in result.map or in result.code but not in both
keeping the `/*# sourceMappingURL=component.svelte.map */` magic comment 
~~makes the browser display wrong mappings~~
\*can\* make the browser display wrong mappings, if the sourcemap file exists (`component.svelte.map`)
~~(there is another bug with sourcemaps, so mappings are still wrong in the browser)~~
fixed by https://github.com/sveltejs/rollup-plugin-svelte/issues/175
> sass: remove sourceMappingURL from result.code

- docs/preprocessing.md
* Expanded the example of using multiple preprocessors. It was difficult to compare to the example of using only one preprocessor because so much was different beyond just adding a second preprocessor and providing them via an array
* Added `babel` which was missing from the list of preprocessors
* Added a missing comma in the list of preprocessors
* Removed the example of `sveltePreprocess` because there was already an example of how it's called, so it didn't add much and was a little confusing to have multiple examples to have to read
* Showed where options are passed with `{ ... }`. The example above did the same, so this made it easier to compare
* Mentioned up-front that you need `postcss` for the global rule. Turned the footnotes into bullets - there was no corresponding number in …
> Update preprocessing documentation

- CHANGELOG.md
- package.json
- src/autoProcess.ts
- src/modules/language.ts
- test/transformers/postcss.test.ts
Fixing this made me think it's time for a major rethink/rewrite on how we run the transformers in auto preprocess mode. The current way to run postcss after a style preprocessor seems brittle and, for a lack of a better word, wrong.
> fix: 🐛 language custom transformer overriding postcss

- docs/preprocessing.md
In the `preprocessing.md` doc there seems to be a destructuring error. 
```javascript
const { js: code } //... js doesn't exist
return { code };
```
Using the code above makes it so that the compiler throws errors. The latest esbuild [transform api](https://esbuild.github.io/api/#transform-api) doesn't return an object with the `js` property but instead has the `code` property. 
The small changes below fixes the error and actually mirrors some of the code in the *custom preprocessors* section slightly above the esbuild example.
```javascript
const { code, map } = //...
```
> fix destructuring errors in esbuild example in preprocessing.md

- docs/getting-started.md
I'm following the final example on this page, which uses {name} in the template. I don't think there's a `world` variable, but I could be wrong 🌎
> Docs: getting-started.md - Change examples to use {name} variable

- src/transformers/typescript.ts
- test/fixtures/tsconfig.extends1.json
- test/fixtures/tsconfig.extends2.json
- test/transformers/typescript.test.ts
Fixes #300
I was unsure about the boolean/string behavior of the options, especially because it is mentioned nowhere in the docs that boolean is a valid option.
Also, if I understand this correctly, by default the tsconfig.json is not picked up if I do `sveltePreprocess()`?
> (feat) Support tsconfig extends

- src/transformers/scss.ts
> fix: 🐛 prevent svelte file from being added to scss dep list

- docs/usage.md
Make it clear that svelte.config.js instructions work for vscode and kit as I didn't see this anywhere else.
> Clarify usage of svelte.config.js

- package.json
Reverts part of #395
I don't know why the peer dependency was bumped, I don't think it was necessary and it's a breaking change, so we should revert it
> (fix) relax TS peer dep requirement

- src/transformers/typescript.ts
- test/fixtures/tsconfig.outdir.json
- test/transformers/typescript.test.ts
As mentioned in #405. Since it's a quick fix I decided to just submit the PR before any discussion. Happy to discuss more if you're not sure if this is the right thing to do.
If outDir is set, Typescript sets directories in the source maps relative to it
which causes problems in `concatSourceMaps` when the paths in the source
point to nonexistent files instead of the virtual modules set up by the
transformer.
Tested against https://github.com/dimfeld/svelte-preprocess-injected-bug and also added a new unit test.
Fixes #405
> (fix) Clear outDir if set in tsconfig

- src/transformers/typescript.ts
This prevents the code from being transpiled as es3 in this situation, which makes the `const $$$$$ = ..` separator get transformed into `var $$$$$ = ...` which then is no longer split out. This situation came up in the tests of `svelte-jester`.
No test added, because it's not really possible, because there's a tsconfig in this repo which would be found.
> (fix) return default settings when no tsconfig found

- src/transformers/coffeescript.ts
Fixes #413
The coffeescript transformer was using an old sourcemap format I believe. It was something like:
```
SourceMap {
lines: [
LineMap { line: 0, columns: [Array] },
<1 empty item>,
LineMap { line: 2, columns: [Array] }
]
}
```
This change uses the `v3SourceMap` string from the compile result instead.
> fix: coffeescript sourcemap

- src/transformers/typescript.ts
- test/fixtures/TypeScriptES2021.svelte
- test/fixtures/tsconfig.es2021target.json
- test/transformers/typescript.test.ts
Resolves #383.
I moved all of the default options down to line 269, since the current behavior gave unusual precedence to the defaults where they would override options from tsconfig, but not options directly passed to the preprocessor, which feels unintuitive. I can move the `moduleResolution` setting back though, if you disagree.
~~This could be considered semver-major, since moving the default target to ES2021 would cause problems if anyone was inadvertently relying on ES6 transpilation to demodernize their JS and didn't have a proper Babel step or something in the bundler.~~
> Don't overwrite `target` settings from tsconfig.json

- docs/preprocessing.md
- examples/sapper-rollup/src/routes/blog/index.svelte
- examples/svelte-rollup/src/App.svelte
- src/modules/language.ts
- test/transformers/typescript.test.ts
FIxes #414
I think the language detection and the auto preprocessor are still in the need of a significant refactor, but this should be enough for now.
> fix: deprecate type attribute

- src/transformers/typescript.ts
When using the advanced import preprocessor, make sure to use a high resolution source map.
Else the mappings won't be that good anymore (line mappings at best).
Maybe related to #421
> fix: generate high resolution source map

- docs/preprocessing.md
- src/transformers/pug.ts
Closes #447
Also add note about a pug limitation using template literals
> fix: better pug error message

- src/transformers/typescript.ts
- test/fixtures/TypeScriptImports.svelte
- test/transformers/typescript.test.ts
Fixes https://github.com/sveltejs/svelte/issues/7120
the original regex had `+-=`, which forgot to escape `-`, resulting ignoring any characters between `+` to `=`
> fix: ts preprocessor to consider store suffixed with number

- src/transformers/babel.ts
- test/transformers/babel.test.ts
This PR provides `options.caller` to Babel when transforming files, it's what `@rollup/plugin-babel` does [here](https://github.com/rollup/plugins/blob/8c6ae32f96ab299ca0b1207857e242bac89b9ca7/packages/babel/src/index.js#L62-L69) and what webpack's `babel-loader` does [here](https://github.com/babel/babel-loader/blob/eafd20d4877497f6c504a37611c2430e38446a7c/src/injectCaller.js#L7-L23)
When this is configured on the caller's side (`svelte-preprocess` in this scenario) then `@babel/preset-env` won't touch certain language features by default - they will still be transpiled if there is an explicit configuration to do so.
This allows for people to maintain a single Babel config where each tool can opt-out of certain transforms. For instance, with the config used in the added test modules …
> feat(babel): provide caller information to Babel

- src/transformers/typescript.ts
- test/fixtures/TypeScriptImports.svelte
Fixes #466
And also fixes another situation that led me to research this issue. Where something like this
```ts
let str = "$1$2";
```
or
```ts
let str = "$1a";
```
would result in a type error (TS1351) where it was assuming that `1$2` was a variable where it should not
> fix: add # and numbers to ts store regex

- README.md
- src/modules/utils.ts
- test/autoProcess/externalFiles.test.ts
Closes https://github.com/sveltejs/kit/issues/4062
The `isValidLocalPath` was checking the path validity the other way around (not remote). We should instead check if it's a valid local path (starts with `.` and doesn't contain interpolation).
> fix: only try to load external files with relative paths

- src/transformers/less.ts
Solves #495
Looks like the issue only affects imports from node_modules. Can't make a test without adding a dependency to the project.
> fix: always use absolute paths for less imports

- src/transformers/globalStyle.ts
- src/transformers/postcss.ts
When using Vite's  new [devSourcemap](https://vitejs.dev/config/#css-devsourcemap) you'll be getting warnings like:
```
Sourcemap for ".../src/routes/__layout.svelte" points to missing source files
```
Example SvelteKit project: https://github.com/bfanger/svelte-project-template 
```js
// svelte.config.js
/** @type {import('@sveltejs/kit').Config} */
export default {
preprocess: preprocess({ sourceMap: true }),
kit: {
vite: { css: { devSourcemap: true } },
},
};
```
When no `to:` is passed to `postcss()`, PostCSS will use NodeJS current working directory as fallback, which generates  invalid paths. 
This PR adds the `to` parameter, which allows PostCSS to generate the correct relative paths into the sourcemap sources array.
> fix: paths in postcss sourcemap sources array (Sourcemap ... points to missing source files)

- src/transformers/globalStyle.ts
- test/transformers/globalStyle.test.ts
Fixes #236
```svelte
<style lang="scss">
:global {
@font-face {
font-family: "Open Sans";
src: url("/fonts/OpenSans-Regular.woff2") format("woff2"),
}
}
</style>
```
Currently generates:
```css
@font-face {}
```
Instead of the desired:
```css
@font-face {
font-family: "Open Sans";
src: url("/fonts/OpenSans-Regular.woff2") format("woff2"),
}
```
"you shouldn't need to use `:global` for `@font-face`" was the reason for closing #236 
And while this is an ok solution for when the `@font-face` is written inside the svelte component, I've encountered this issue when using the following pattern from the Readme:
```svelte
<style lang="scss">
:global {
@import 'global-stylesheet.scss';
}
}
```
All the `@font-face` rules in global-stylesheet.scss are currently being emptied by svelte-preprocess. …
> fix: @font-face inside :global block

- package.json
Fix #519
Checking the code changes in postcss-load-config, this should be enough to suppress peer dep issues.
> feat: support postcss-load-config 4

- src/transformers/stylus.ts
The stylus preprocessor didn't resolve fully sourcemap dependencies, which could cause bugs when using Stylus as preprocessor with Svelte.
https://github.com/sveltejs/svelte-preprocess/pull/500#issuecomment-1119410260
> fix: stylus relative sourcemap sources

- README.md
I think the URL for the preprocess API docs changed at some point. Clicking it takes me to the top of the docs page. I've replaced it with what I believe to be the correct URL.
Apologies for not creating an issue for this, it didn't strike me as providing value for such a small change.
> Fix link to preprocess API docs

- docs/preprocessing.md
hint for where to find additional sass / scss compiler options.
this was very confusing for me, since the docs suggest that you can pass **importers** to the sass preprocessor and gave a different type definition from what svelte-preprocess expects.
taking the following code snippet from the [current sass docs](https://sass-lang.com/documentation/js-api/interfaces/FileImporter) does not work:
```javascript
preprocess({
scss: {
importers: [{
// An importer that redirects relative URLs starting with "~" to
// `node_modules`.
findFileUrl(url) {
if (!url.startsWith('~')) return null;
return new URL(url.substring(1), pathToFileURL('node_modules'));
}
}]
}
})
```
while something like this would:
```javascript
preprocess({
scss: {
importer: (url) => {
console.log(url)
return {
file: url
}
}]
} …
```
> docs(updated link to compiler options for scss & sass)

- docs/preprocessing.md
Fixes #563: The doc had incorrect/outdated information about the `renderSync` option). The update notes that `renderSync` is always used as of svelte-preprocess 5.0.0.
While addressing this, I also added a more specific cross reference link for users to see which options can be passed: https://sass-lang.com/documentation/js-api/interfaces/LegacyStringOptions
I also removed the table, since that formatting now longer seemed useful, and made other minor wording adjustments to this section.
> docs: Update documentation about Sass options

- package.json
- pnpm-lock.yaml
Fixes #582.
My best guess is that `@types/sass` was included in `dependencies` (and not `devDependencies`) as a convenience for users. With types now being included in the main `sass` package, it should no longer be an issue that people might have `sass` without the types, so we can safely remove the types here without promoting `sass` from `devDependencies` to `dependencies`. 
This removes the warning described in #582.
> fix: remove deprecated package @types/sass

- jest.config.js
- package.json
- pnpm-lock.yaml
- src/transformers/typescript.ts
- test/transformers/typescript.test.ts
For #586. Also bumping to jest 29 because ts-jest 27 doesn't support TypeScript 5
> fix: address breaking changes in TypeScript 5

- CHANGELOG.md
- src/transformers/pug.ts
*I am Japanese and not good at English, so I am translating at DeepL.
I am afraid this is a minor thing, but I found a spelling mistake and corrected it. ("identation" corrected to "indentation").
If this is my mistake, please close this PR.
> fix: spell. "identation" → "indentation "

- package.json
- src/transformers/scss.ts
Should close #619
Argh, just remembered that this is hard to reproduce in tests for some reason: https://github.com/sveltejs/svelte-preprocess/blob/main/src/transformers/scss.ts#L72
> fix: sass dependency list referencing source file in win32

- src/modules/globalifySelector.ts
- test/modules/globalifySelector.test.ts
Fixes #501
I ran into an issue where I could not use simple tailwind apply directives for dark mode and also couldn't import Daisy UI. I tracked it down to a problem with `svelte-preprocess` creating `:global` rules that svelte is not happy with. User https://github.com/MagDevX suggested an adjustment to `globalifySelector.js` `combinatorPattern` to prevent selectors with parenthesis from being split.
> fix: Adjust globalifySelector to not split selectors with parentheses.

- README.md
- docs/getting-started.md
- docs/migration-guide.md
- docs/preprocessing.md
- docs/usage.md
- package.json
- src/index.ts
- src/processors/babel.ts
- src/processors/coffeescript.ts
- src/processors/globalStyle.ts
- src/processors/less.ts
- src/processors/postcss.ts
- src/processors/pug.ts
- src/processors/replace.ts
- src/processors/scss.ts
- src/processors/stylus.ts
- src/processors/typescript.ts
- test/autoProcess/autoProcess.test.ts
- test/autoProcess/externalFiles.test.ts
- test/autoProcess/markup.test.ts
- test/autoProcess/script.test.ts
- test/autoProcess/sourceMaps.test.ts
- test/autoProcess/style.test.ts
- test/transformers/babel.test.ts
- test/transformers/less.test.ts
- test/transformers/postcss.test.ts
- test/transformers/pug.test.ts
- test/transformers/scss.test.ts
- test/transformers/stylus.test.ts
- test/transformers/typescript.test.ts
This deprecates the default export in favor of the new named export `sveltePreprocess`. It's done to ensure a better interop between CJS and ESM without resorting to hacks in the future. It also enables people using `"module": "NodeNext"` in their `tsconfig.json` to import without type errors. The sub exports were also adjusted so that the transpiled TS output doesn't include `__importDefault` wrappers, which makes Node's static analysis miss those named exports.
Related: https://github.com/sveltejs/svelte-preprocess/issues/591#issuecomment-2166807552
> fix: deprecate default export in favor of named export

- src/transformers/typescript.ts
- test/transformers/typescript.test.ts
...in order to prevent invalid config errors which could arise from us forcing a module resolution. fixes #646
> fix: remove customConditions tsconfig option

- src/transformers/typescript.ts
In case no tsconfig is found whatsoever, enable `verbatimModuleSyntax` to prevent stripping unused imports.
Also fix a related issue where the config passed manually was not properly parsed.
Also print warning message in bold to make it more visible.
related to #643
> chore: fall back to verbatimModuleSyntax if possible

- package.json
- pnpm-lock.yaml
- src/modules/prepareContent.ts
- src/transformers/pug.ts
- src/types/modules.d.ts
these are such tiny utils it doesn't feel worth adding three dependencies (one has a transitive dependency of its own)
> chore: remove all dependencies

- docs/usage.md
Updates documentation example to correctly use changes from PR #641
PR #641 change the example to have `import { sveltePreprocess } from 'svelte-preprocess'` instead of `import preprocess from 'svelte-preprocess'`, but missed one spot where `preprocess` needed to change to `sveltePreprocess`.
> fix: update broken documentation example

- docs/preprocessing.md
- src/transformers/pug.ts
> pug mixins to support svelte-5 #snippet and @render

- package.json
- pnpm-lock.yaml
- src/transformers/scss.ts
Quick fix for now, in the mid term we should add proper support for the new API. @kaisermann if you remember what you did back then and how it translates to the new API, I would be grateful for a PR 😄 
fixes #656
> fix: ignore sass deprecation warning
